comixcraft/Editor

README.md
In this PR I just updated the README to include the hosting.
=> CXC-308: hosting

components/TextEditor.vue, components/WrapperCanvas.vue, utils/Classes/Element.js, utils/Classes/Panel.js, utils/Classes/Position.js
- Remove getCurrentState() method for Element (and panel) classes
- Remove all method that should have been setters (setWidth, setPos...)
- Edit WrapperCanvas to use setters instead of outdated methods
=> Refactor Element and Position classes

assets/scss/_variables.scss, components/ComicPanels.vue, components/WrapperCanvas.vue, config/templatePanelConfig.js, config/templateStripConfig.js
panels of any size are now always taking up the most space that is available to them
=> CXC-309: responsive panels

components/DragResizeRotate.vue
- added a function to detect when tapping occured twice
=> fix: double clicking doesnt work on iphone

components/CatalogLayout.vue, components/CatalogSearch.vue, components/CatalogSubNavigation.vue
Now if you are switching between sub-categories filters are reset and search term is cleared on categories changed. Please review.
=> CXC-364-Reset-filter-and-search-on-each-change

components/ComicPanels.vue
In line 34 of the ComicPanels component I added a +1 to the index. Didn't run into any bugs or make any other changes :)
=> CXC-388-Change-count-of-panels

pages/index.vue
I changed the default selection behavior from when to choose the draft and when the single panel.
- when draft => select draft
- when draft deleted => select single panel
- when no draft => select single panel
=> CXC-384: template and draft selection

components/DecisionPopUp.vue, components/OverlayModal.vue
I adjusted the pop-up on desktop with a better design.
I implemented the design changes like in defined in [Figma](https://www.figma.com/design/GOjCRAhy58negMzbKPEiBl/Comixcraft?node-id=1752-4048&t=sQcStZYZbT3hyZaI-0). 
I did not take any content changes into account that would occur between the desktop and the current mobile version.
=> Cxc 382 pop up styling on desktop

components/LayerObject.vue
Tested on mac: Chrome / Safari. Some bugs exist but are also on dev (see bugs sheet)
Test on mobile: https://stunning-creponne-5c99ae.netlify.app/
Improvement: A design for the ghost class (the layer are duplicated when dragged, maybe a better option can be decided?)
=> add: drag and drop for layer option

components/CatalogImagePreview.vue, components/DecisionPopUp.vue, components/DragResizeRotate.vue, components/LayerObject.vue, components/TemplateDisplay.vue, pages/index.vue
add draggable="false" to all ing elements
=> Made elements non-draggable

components/CatalogLayout.vue, pages/editor.vue, pages/export.vue
Could not replicate behavior on phone
=> add user-select: none to topnav and search

components/CatalogImagePreview.vue, components/CatalogNavigation.vue, components/CatalogSearch.vue, components/CatalogSubNavigation.vue, components/DragResizeRotate.vue, components/TemplateDisplay.vue, pages/editor.vue, pages/index.vue
- Check the sub navigation selection behavior on mobile (without hover)
- Check if there is no hover of assets on the editor page on mobile (selecting two assets at the same time)
- Check on the Index page, if there is no hover on mobile (selecting two panels at the same time)
- Review all hover states for any unusual behavior
- Ensure the hover state for undo/redo on the desktop is functioning as expected (increase size on hover)
=> CXC-424 Adjust Hover States for subnavigation and navigation

components/CatalogSearch.vue
- I moved the filter icon to the right
- Filter icon is only shown, when it is possible to filter
- Remove unused filterable property
- Restructured input with close button
=> CXC-427: rework of filter icon

components/CatalogContainer.vue, pages/editor.vue
Have a look if in your opinion the text size of text is too big for the desktop version.
=> Cxc 421 catalog does not look good when there is no search result

components/CatalogContainer.vue, components/CatalogLayout.vue, components/PreviewCanvas.vue, components/SpinnerLoader.vue, pages/editor.vue, pages/export.vue, pages/index.vue
I extracted the loading animation from PreviewCanvas in it's own component to be reused in multiple places.
This required me to do some refactoring in the PreviewCanvas component.
I also had to adjust some things on the CatalogContainer to center the loading animation.
=> CXC-426: add loading animation for catalog

pages/export.vue
The share functionality was from Juju implemented and the text on the download button is now "download PNG"
=> Cxc 430 info of export format + CXC 191 Sharing functionality

components/DecisionPopUp.vue, components/DragResizeRotate.vue, components/EditionMenu.vue, components/PreviewCanvas.vue, components/WrapperCanvas.vue, nuxt.config.js, utils/Classes/Panel.js, utils/Classes/Text.js
A lot of changes here: 
please test on all devices for : 
- make sure preview worked with chosen text-alignment
- make sure undo/redo works for this steps as well
- make sure the downloaded comic fit as well
=> CXC-448-Allow-user-to-chose-text-align-left-center-right-or-have-center-as-default

assets/scss/_variables.scss, components/CatalogSubNavigation.vue
Changed the design to make them stand out more/ be more visible.
=> CXC-438-Redesign-subcategories

pages/export.vue
I added a feedback button on top of the export page which links to our form. I created one class for it in the styling section so it can be removed easily as well.
=> add feedback button to export page

components/WrapperCanvas.vue
* fix error with pointer-events
* fix with target check
=> Bugfix for unknown

assets/scss/_button.scss, pages/export.vue
=> CXC-476-Hover-on-export-on-mobile

components/CatalogLayout.vue
Fixed grammar in search placeholder.
=> Cxc 475 change search placeholder
